/*Given a string, we have to find out all its subsequences of it.
A String is a subsequence of a given String,
that is generated by deleting some character of a given string without changing its order.

Input: abc
Output: a, b, c, ab, bc, ac, abc.*/

#include <iostream>
#include <vector>
#include <algorithm> // for sorting
using namespace std;

// Recursive function to generate all subsequences
void f(string &str, int i, string result, vector<string> &li) {
    if(i == str.length()) {
        li.push_back(result); // store the current subsequence
        return;
    }

    // Include current character
    f(str, i + 1, result + str[i], li);

    // Exclude current character
    f(str, i + 1, result, li);
}

int main() {
    vector<string> res;
    string str = "abc";

    f(str, 0, "", res); // generate all subsequences

    // sort for neat output
    sort(res.begin(), res.end());

    // Print all non-empty subsequences
    for(const string &s : res) {
        if(!s.empty()) cout << s << " ";
    }

    return 0;
}

// Here's what each parameter does:
// • str     : The original input string (e.g., "abc").
// • i       : The current index in the string being processed.
// • result  : The current subsequence being built (accumulates characters).
// • li      : The list (vector) where all valid subsequences are stored.